spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://${prod_db_host}:${prod_db_port}/${prod_db_name}
    username: ${prod_db_username}
    password: ${prod_db_password}
    name: clone-backend

okta:
  oauth2:
    issuer: https://dev-m3p6dptt4vt1z8gl.us.auth0.com/
    client-id: ${auth0_client_id}
    client-secret: ${auth0_client_secret}
